/*PARAMETROS DE SALIDA*/

SET @RESULTADO = 0;

DELIMITER //
CREATE PROCEDURE CALCULAR_ALUMNOS(IN p_codigo INT, OUT res DECIMAL)
BEGIN
	SELECT COUNT(*) INTO RES FROM ALUMNOS WHERE COD_CURSO = p_codigo;
END//

DELIMITER ;

CALL CALCULAR_ALUMNOS(10, @RESULTADO);

SELECT @RESULTADO;

/*
	SELECT INTO
			variable
            fichero
            dumpfile
*/

SET @VAR = 10;
SET @VAR2 = ' ';

SELECT @VAR;
SELECT @VAR2;

SELECT 23 INTO @VAR;

SELECT 45, 'CONQUER' INTO @VAR, @VAR2;

SELECT @VAR, @VAR2;
